# Generated by Django 2.2.7 on 2019-11-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('brand_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('site', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('contact', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('chicken_status', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('beaf_status', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('mutton_status', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('horsemeat_status', models.CharField(blank=True, default='', max_length=512, null=True)),
            ],
            options={
                'ordering': ('company_name',),
            },
        ),
    ]
